### ISSUE TITLE
phys prop: electrical conductivity purpose

### ISSUE THREAD

**Issue by sdevriese** [geoscixyz/em#257]
![image](https://cloud.githubusercontent.com/assets/13733333/17949878/7fbaf8be-6a0c-11e6-88de-c330ac3d4877.png)

@dccowan Did you work on this page? Can you help complete the purpose statement?

**Comment by dccowan** [comment]
@sgkang @thast  It wasn't me who worked on this. Did one of you work on this? If so, please contact Sarah regarding issue.

**Comment by lheagy** [comment]
@sgkang: it looks like you were the primary author here. Can you comment on this issue?

**Comment by dccowan** [comment]
The physical properties section was completed in PhysPropsEdits branch. Included is a final edit of all information pertaining to electrical conductivity. The organization among all three physical properties is uniform. This branch has since been merged into master.
