### ISSUE TITLE
Maxwell 1: Fundamentals - Refactoring 

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/em#346]
This is a large tracking-issue. The items will later be parsed into smaller bite-sized issues. 
- [ ] Formative Laws needs an intro on the index page
- [ ] move interface conditions out of Formative Laws
- [ ] Pull everything under "Maxwell's equations" up a level. The toctree should now be
    - Formative Laws
    - Time-domain equations
    - Frequency domain equations
    - interface conditions 
    - wave equation (quasistatic, wave regime, wavenumber, skin depth...) much of this content is currently in "plane wave sources" and should be elevated a level. 
    - plane wave sources in homogeneous media
    - dipole sources in homogeneous media
- [ ] Index page for plane wave sources and dipole sources need a **Purpose** and a **Setup** 
- [ ] plane wave index page "Solving plane wave equations" can be made more concise. Much of this content can be introduced in "Maxwell's equations in frequency" and "wave equation" and linked.

**Comment by sgkang** [comment]
Another item that we have to deal with in the Maxell 1: Fundamental is "Reflection and refraction of plane waves"

**Comment by lheagy** [comment]
@sgkang , @dccowan : can you update me when the dipole and sphere material is in? This issue cannot be addressed until they are in (otherwise we will make a big mess!) This means that 
- [ ] #69 and 
- [ ] #70 
need to be cleaned up and merged in cc @dccowan

**Comment by dccowan** [comment]
Finalized re-organization of Maxwell 1: Fundamentals was taken care of in MaxwellFundamentalsEdits branch. This branch has been reviewed by @lheagy and merged into master.
