### ISSUE TITLE
Interface conditions: normal component of the current density 

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/em#395]
The normal component of the current density missing from interface conditions.

![image](https://cloud.githubusercontent.com/assets/6361812/21290477/b114523e-c470-11e6-8f4c-cb669fbc1f4d.png)

Some material is already in http://em.geosci.xyz/content/maxwell2_static/governing_equations/interface_conditions.html. This should be re-organized to be consistent (see #346)

**Comment by dccowan** [comment]
This was handled within MaxwellFundamentalsEdits branch. Interface conditions for the current density were added.
