### ISSUE TITLE
Missing case history: Noranda

### ISSUE THREAD

**Issue by sgkang** [geoscixyz/em#444]
This case history is used in DISC2017, but not exists in em geosci. Needs to be updated !!

**Comment by sdevriese** [comment]
I'll draft it in google docs. It's from Elliot's thesis. @dougoldenburg thoughts on this?

**Comment by sdevriese** [comment]
Draft has been created.
https://docs.google.com/document/d/13A0YtHHgQ8PW9KkbzF5sCzMHwPWHydXjBHZfnRmIrkw/edit?usp=sharing

**Comment by thast** [comment]
@sdevriese : can this issue be closed now?

**Comment by sdevriese** [comment]
Yep!
