### ISSUE TITLE
Noranda

### ISSUE THREAD

**Issue by dougoldenburg** [geoscixyz/em#447]
Can you take the 3D model from the ZTEM inversion and plot it as a cube with one corner extracted so that the 3D geology can be seen. Also make it clear where 275 m depth slice is.  Maybe plot the model from the surface to about 1km (or less)

![image](https://cloud.githubusercontent.com/assets/8864444/22630731/dcf8906c-ebb3-11e6-9bee-761c85e3ca07.png)

**Comment by sdevriese** [comment]
I'll try to locate the models on Elliot's old computer.

**Comment by sdevriese** [comment]
@dougoldenburg Thoughts on this?

![noranda3d](https://cloud.githubusercontent.com/assets/13733333/22710610/c996d8d2-ed32-11e6-84a2-f61ca78ec6c1.png)

- shows about 1300 m vertically
- top shows depth slice at -225
- Black like shows where -475 m is

**Comment by sdevriese** [comment]
![image](https://cloud.githubusercontent.com/assets/13733333/22757084/4f83387a-edfe-11e6-9a36-7d49227cdfd9.png)
