### ISSUE TITLE
GPR physical properties table

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/em#448]
Can we update the order of columns to be 
- relative permittivity 
- velocity
- conductivity
- penetration depth 
![image](https://cloud.githubusercontent.com/assets/6361812/22630776/9bc60fe2-ebb4-11e6-9eea-7f7440c58bb3.png)

**Comment by lheagy** [comment]
Could you please add this table to the dielectric permittivity page (http://em.geosci.xyz/content/physical_properties/electrical_permittivity/electrical_permittivity_units_values.html)?

I believe the original is from the gpg 

![image](https://cloud.githubusercontent.com/assets/6361812/22718217/f7369086-ed53-11e6-8b3c-2c59370c3bd2.png)

**Comment by dccowan** [comment]
Content from the GPG has been transferred into EMgeosci and the physical properties table has been made. This could be revisited in the future but is good for now.
