### ISSUE TITLE
Physical Properties: Magnetic permeability units

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/em#464]
I think this statement is potentially quite confusing: 
`The correct SI units for magnetic susceptibility are (A/m)/(A/m). However, it is commonly expressed as a unitless quantity.`
http://em.geosci.xyz/content/physical_properties/magnetic_permeability/magnetic_permeability_units.html 

`(A/m) / (A/m)` is unitless. Is there another point trying to be made here? Otherwise, I think this should be revised to simply state that Magnetic susceptibility is unitless

thoughts @fourndo, @dccowan ?

**Comment by dccowan** [comment]
SI units for susceptibility are (A/m)/(A/m). This is another way of re-enforcing the fact that it is the magnetization/field. We write it as unitless out of convenience. This was something Randy was adamant about when I was writing up my thesis.
