### ISSUE TITLE
Un-polarized --> Non-polarized

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/em#465]
Correct me if I am wrong, but I think this should be non-polarized (`un` to me implies that the polarization was somehow removed rather than a molecule simply not having a polarization) 
http://em.geosci.xyz/content/physical_properties/dielectric_permittivity/index.html

![image](https://cloud.githubusercontent.com/assets/6361812/23333578/6cbc4160-fb42-11e6-8aad-7450d7825365.png)

**Comment by dccowan** [comment]
Made the change and committed it
