### ISSUE TITLE
Maxwell I: Fundamentals Restructuring

### ISSUE THREAD

**Issue by dccowan** [geoscixyz/em#466]
I strongly believe we should consider a restructuring of the current Maxwell's I: Fundamentals. Sub-levels containing the actual content are great but some work could be done on the highest level. I am proposing the following structure:

- Formative Laws
- Maxwell's Equations in Different Forms (formally "Quick guide to Maxwell's equations". I felt this section was placed too late)
- Maxwell's Equations in Time
- Maxwell's Equations in Frequency
- Plane Waves in Homogeneous Media
- Maxwell's Equations with Source Terms
- Dipole Sources in Homogeneous Media
- Solving Maxwell's Equations

Essentially, I would like to move "Quick guide to Maxwell's" and change the name. We thoroughly presented the formative laws. Defining Maxwell's equations right after is a good segway for the remainder of the section since everything done afterwards uses Maxwell's equations as a starting point. After we do the plane waves section, I would like to add "Maxwell's equations with source terms". This explains what the source terms are and segways into the dipole sources in homogeneous media.

**Comment by lheagy** [comment]
Thanks @dccowan. I agree that moving the "Quick Guide to Maxwell's equations" is a good idea.

I think we should give some thought to titles (Having "Maxwell's Equations in ..." starts making them quite long). 

I also think that we should leave Time-Domain equations before Frequency Domain equations - arguably, they are more intuitive as you can think about processes happening through time (thinking in the fourier domain is tougher). 

Perhaps: 
- Formative Laws
- Overview of Maxwell's Equations
- Time Domain Equations
- Frequency Domain Equations
- Plane Waves in Homogeneous Media
- Dipole Sources in Homogeneous Media
- Solving Maxwell's Equations

cc @dougoldenburg, @sgkang

**Comment by dccowan** [comment]
I was also wondering if it would be beneficial to combine "time-domain equations" and "frequency-domain equations" into something called "electromagnetic wave equation". Essentially what you are showing here is that by combining Faraday's law with the Ampere-Maxwell equation, we get a wave equation. The equivalent expression in the frequency domain is the Helmholtz. This segways nicely into the plane waves in homogeneous media section.

**Comment by lheagy** [comment]
In a lot of ways, I think it is beneficial to keep them separate, in particular for people who are new to the subject. We typically divide methods into "time domain" and "frequency domain", so having specific places for each of these in the fundamentals is potentially quite helpful for someone who starts from "Geophysical Surveys" and is drilling down to the fundamentals

**Comment by dccowan** [comment]
People seemed to be on board for the new restructure.
Further issues can be addressed in MAXWELL FUNDAMENTALS STATUS issue
