### ISSUE TITLE
Contributors: Placeholder image does not exist 

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/em#467]
![image](https://cloud.githubusercontent.com/assets/6361812/23439470/a695ccb8-fdcb-11e6-8745-e3a9951d4849.png)

https://github.com/geoscixyz/em/raw/PlaceHolderAvatars/images_contributors/placeholder.png

**Comment by dccowan** [comment]
I created a pull request for fixing it right now. I forgot to switch the path from my local branch to master. Please grant permission.

**Comment by lheagy** [comment]
thanks devin! I have approved #468

**Comment by dccowan** [comment]
Error has been fixed. Placeholder images are on live EM geosci
