### ISSUE TITLE
skin depth and diffusion distance

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/em#477]
Right now, there are not easily found pages on skin depth and diffusion distance. (eg. `Skin Depth` is not anywhere to be found on the navigation bar). I think it would be valuable to have these concepts accessible at a high level within em geosci. @dccowan, what are your thoughts on including a page titled "Skin Depth" and another titled "Diffusion Distance" in the fundamentals?

**Comment by dccowan** [comment]
Skin depth and diffusion distance can be found within "plane waves in homogeneous media". I was planning on looking into that soon. We can meet up and discuss organization aspects of this content if you want.

**Comment by lheagy** [comment]
Sounds good! I am around this aft if you would like to chat, or we can aim for tomorrow.

**Comment by dccowan** [comment]
This has been addressed in the restructuring of Maxwell Fundamentals. These should be much easier to find and there are a significant number of hyperlinks to them as well.

**Comment by lheagy** [comment]
Awesome, thanks @dccowan!
