### ISSUE TITLE
Discussion on pages

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/em#484]
We could add a discussion thread to each page using: https://disqus.com/. One example is actions is the Astropy tutorials: http://www.astropy.org/astropy-tutorials/Quantities.html. Thoughts??

![image](https://cloud.githubusercontent.com/assets/6361812/25165211/23b7d60c-248a-11e7-9420-b288dec604f1.png)

**Comment by dccowan** [comment]
I like this idea. I think it would promote more contribution from outside sources. However, I feel we should leave discussion boards on higher levels within the contents hierarchy.

**Comment by lheagy** [comment]
This closed with #490
