### ISSUE TITLE
missing figure

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/em#495]
http://em.geosci.xyz/content/maxwell1_fundamentals/plane_waves_in_homogeneous_media/frequency/analytic_solution.html#frequency-domain-plane-wave-sources-wavenumber

![image](https://cloud.githubusercontent.com/assets/6361812/25598945/2a89a1f6-2e8d-11e7-92d0-aca2c1917a84.png)

**Comment by dccowan** [comment]
I'm not sure what image is supposed to be here. If I made the image, it would be found in ../images. Did somebody delete it? Is the image necessary or do the equations themselves describe the wave properties sufficiently?

**Comment by lheagy** [comment]
@sgkang, do you know what this image should be?
