### ISSUE TITLE
Inconsistent simulation results from DC_Layer_Cylinder_2_5D.ipynb and DC_LayeredEarth.ipynb

### ISSUE THREAD

**Issue by jiajiasun** [geoscixyz/em#535]
I used DC_Layer_Cylinder_2_5D.ipynb to simulate a simple dipole-dipole survey over a homogeneous halfspace of 500 ohm*m. The locations of the A, M, N, B electrodes are, respectively, -30.25, -10.25, 10.25, 30.25 m. The following picture summarizes the results.

![dipoledipole](https://user-images.githubusercontent.com/379368/44824971-e5fcde80-abcd-11e8-85a6-5820de9c786d.png)

According to the results shown above, the potentials at M and N electrodes are 2.3 V and - 2.3V. The voltage between M and N electrodes is, therefore, 4.6 V.
Then I calculated the apparent resistivity in the following way:  4.6 * 2 * pi / (1/20-1/40.5-1/40.5+1/20) = 571 Ohm*m, whereas what I expected to obtain is 500 because of the homogeneous halfspace. 

I also tested it using DC_Plate2_5D.ipynb, and obtained the same result, i.e., 571 Ohm*m instead of 500.

Interestingly, when I tested it using DC_LayeredEarth.ipynb, with almost the exact same set-up (the only difference is that the electrodes' locations are now -30, -10, 10 and 30),  I obtained something different (shown below). 

![dipolelayeredearth](https://user-images.githubusercontent.com/379368/44825234-4c363100-abcf-11e8-9da1-f7c79407c32e.png)

It can be seen that the potentials at M and N electrodes are now 2.0 V and -2.0 V. Following the same procedure, I calculated the apparent resistivity as follows:  4.0 * 2 * pi/(1/20-1/40-1/40+1/20) = 502.65 which is very close to the expected value, 500. 

It looks to me that, (1) the simulation results are not quite consistent between DC_LayeredEarth.ipynb and DC_Layer_Cylinder_2_5D.ipynb (or DC_Plate2_5D.ipynb), and (2) DC_LayeredEarth.ipynb gives more accurate results. But I could be wrong!

Also, if you look at the current density values in the above two pictures, they are not quite the same.

Could anyone please help me understand what is going on here? Thanks a lot!

**Comment by thast** [comment]
@jiajiasun : 
- `DC_LayeredEarth` uses an [analytic solution (from Telford) ](https://github.com/geoscixyz/em_examples/blob/8d4c069ae9c6175ea73373cb4ce01d3a20a87bf7/em_examples/DCLayers.py#L69) to compute the surface potential from a 2-layered Earth.
- The 2.5D apps are voxel-based. As mentioned before, we use a correction factor to get a proper apparent resistivity value in the upper-right corner of the app. I imagine the error on the measured potentials come from this fact (so do you find that the error is worst for dipole-dipole than for pole-pole?).
- Thus it is no surprise that the surface potentials are more accurate in the `DC_LayeredEarth` apps (up to the number of decimals you have access on the plot).
- However the analytic solution in `DC_LayeredEarth` is only valid for the surface potentials. So for the bottom plot we first compute only a 2D forward (for reactivity) and we use again a correction  factor. This is probably why the streamplots look different, one is 2.5D and the other only 2D.

In our 350 class, we usually use the `DC_LayeredEarth` app for the type of exercise you mentioned before (computing apparent resisitvity from potential difference). 2D apps are used for interactivity and building understanding. 2.5D apps have the best fields approximation.

**Comment by thast** [comment]
@jiajiasun : Thanks for going through all of it! We made a lot of assumptions or trade-off during the building of this apps. We should think of a place to document and archive it (cc @lheagy ).

**Comment by jiajiasun** [comment]
Hi, @thast  Thank you very much for your response and your detailed explanation! Also, thanks for sharing your experiences with DC_LayeredEarth in the 350 class! I am designing the first lab exercise on DC for my class, and I will definitely take a closer look at this app.

Thank you all for all the time and efforts put into all the materials and apps! That is A LOT of work! You all did an awesome job, which makes things easier for people like me.
