### ISSUE TITLE
Case Histories - SEG

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/em#544]
In order to be in-line with the SEG policies, we need to make a few updates: 

- [x] The full citation + DOI should be provided in the "Special Thanks," not just the title and a link. (e.g. This is missing in [Wadi Sabha](https://em.geosci.xyz/content/case_histories/wadi_sahba/index.html)). For formatting, it can be put as a bullet-point and the text can be directly copied from the SEG listing

- [x] all links should be doi's rather than the SEG page. For example in the [Wadi Sabha "Special Thanks"], the SEG url is provided: https://library.seg.org/doi/abs/10.1190/tle35110977.1, but we should be instead providing the doi url: https://doi.org/10.1190/tle35110977.1 (found at the end of the citation)

- [x] We should also add a mention of the DISC, state that the material has been adapted from the original version, and state that the material is subject to SEG terms of use and conditions. Here is a suggestion for Wadhi Sabha that can be used as a template

## Template

**Special Thanks**

Thanks to the [Society of Exploration Geophysics](https://seg.org) for permission to reproduce figures and adapt text from:
- Daniele Colombo , Gary McNeice , Diego Rovetta , Ernesto Sandoval-Curiel , Ersan Turkoglu , and Armando Sena (2016). ”High-resolution velocity modeling by seismic-airborne TEM joint inversion: A new perspective for near-surface characterization.” The Leading Edge, 35(11), 977–985.
https://doi.org/10.1190/tle35110977.1

The material presented here has been modified from the SEG-published version and is subject to [the SEG terms of use and conditions](https://seg.org/Publications/Policies-and-Permissions/Permissions). This case history was presented as a part of the [SEG 2017 Distinguished Instructor Short Course](https://seg.org/Education/Courses/DISC/2017-DISC-Doug-Oldenburg). 

## Overview of the SEG site and what to use
![image](https://user-images.githubusercontent.com/6361812/50110658-a6dfb100-01ef-11e9-890a-8e17bcbe758b.png)

**Comment by dougoldenburg** [comment]
This seems sufficient but so if Devin can accomplish this we may be finished.

**Comment by dccowan** [comment]
I will try to follow this template to comply with SEG. However, some of the source material for the case histories was adapted from unpublished material provided to our group. This has led to obstacles where trying to find permissions and citations.
